// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(PlantCareDbContext))]
    [Migration("20251214171901_RemovedRedundantKey")]
    partial class RemovedRedundantKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DataAccessLayer.Entities.CareAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareActionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareActionTypeId");

                    b.HasIndex("PlantId");

                    b.ToTable("CareActions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.CareActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CareActionTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HealthAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfidenceLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedIssues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HealthScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId")
                        .IsUnique();

                    b.ToTable("HealthAssessments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthAssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.CareAction", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.CareActionType", "CareActionType")
                        .WithMany("CareActions")
                        .HasForeignKey("CareActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Plant", "Plant")
                        .WithMany("CareActions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareActionType");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.HealthAssessment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Observation", "Observation")
                        .WithOne("HealthAssessment")
                        .HasForeignKey("DataAccessLayer.Entities.HealthAssessment", "ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Observation", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Plant", "Plant")
                        .WithMany("Observations")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.CareActionType", b =>
                {
                    b.Navigation("CareActions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Observation", b =>
                {
                    b.Navigation("HealthAssessment")
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Plant", b =>
                {
                    b.Navigation("CareActions");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
